# Generated by Django 3.1.7 on 2021-03-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readers',
        ),
    ]
