# Generated by Django 3.1.7 on 2021-03-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
