# Generated by Django 3.1.7 on 2021-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_post_readers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readers',
        ),
    ]
