# Generated by Django 3.1.7 on 2021-03-24 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0013_auto_20210324_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
