# Generated by Django 3.1.7 on 2021-03-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210324_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPostMark',
        ),
    ]
