# Generated by Django 3.1.7 on 2021-03-24 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0018_delete_userpostmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBlogSubscription',
        ),
    ]
